version: '3'
services:
  typesense:
    image: typesense/typesense:0.25.1
    container_name: typesense_learning
    ports:
      - "8108:8108"
    volumes:
      - ./typesense/data:/data
    environment:
      - TYPESENSE_API_KEY=xyz123
      - TYPESENSE_DATA_DIR=/data
    command: --data-dir /data --api-key=xyz123 --listen-port 8108 --enable-cors